<?php

namespace QuickStart\Pages;

use function QuickStart\Components\Additionals\Mother;

function Error404($props): string
{

    return (<<< HTML
    <Mother>
        <Slot name="title">404 Not Found</Slot>
        <Slot name="stylesheets">
            <link rel="stylesheet" href="/css/index.css" />
            <link rel="stylesheet" href="/css/app.css" />
        </Slot>
        <div class="App-content" >
            <h1>404 - Page Not Found</h1>
            <p>Sorry, the page you are looking for does not exist.</p>
        </div>
    </Mother>
    HTML);
}