<?php

namespace QuickStart\Pages;

use function QuickStart\Components\Additionals\Mother;
use function QuickStart\Components\Home\ThankYou;

function Home($props): string
{

    $name = $props->name ?? 'Guest';

    return (<<< HTML
    <Mother>
        <Slot name="title">Ephect in action!</Slot>
        <Slot name="stylesheets">
            <link rel="stylesheet" href="/css/index.css" />
            <link rel="stylesheet" href="/css/app.css" />
        </Slot>
        <div class="App-content" >
            <code-writer source="/ThankYou/ThankYou.html" use-highlight-js="false" ></code-writer>
            <ThankYou message="%name" />
        </div>
        <Slot name="javascripts">
            <script type="module" src="/modules/human-writes.min.js"></script>
            <script src="ajil.js"
                data-init="doSomething"
                data-depends="/js/fake-dep.js"
                data-sources="/js/home.js"
            >
            </script>
        </Slot>
    </Mother>
    HTML);
}
